#!/bin/bash

sshpass -p "ubnt" ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubnt@192.168.1.20 << EOF
touch /etc/persistent/ct
echo "Enable CT"
cfgmtd -w -p /etc/ -f /tmp/running.cfg
rm -f /etc/ccodes.inc
rm -f /tmp/.sessions.tdb
killall lighttpd
exit
EOF