#!/bin/bash

usr=$1
pass=$2
host='192.168.5.'
port=$3

for i in `seq 1 255`;
do
	echo $i
	sshpass -p $pass scp -o ConnectTimeout=1 -o StrictHostKeyChecking=no -P $port $usr@$host$i:/tmp/system.cfg ~/backup/$i
done    